# Generated by Django 3.1.6 on 2021-02-27 04:57

from django.conf import settings
from django.db import migrations, models
import voting.images


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Primaria'), (2, 'Bachillerato')], default=1)),
                ('candidates_name', models.CharField(max_length=170)),
                ('proposal', models.TextField()),
                ('image', models.ImageField(blank=True, default=voting.images.get_default_candidate_image, max_length=255, null=True, upload_to=voting.images.get_candidate_image_filepath)),
                ('votes', models.ManyToManyField(related_name='candidate_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
