# Generated by Django 3.1.6 on 2021-02-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Primaria'), (2, 'Bachillerato')], default=1),
        ),
    ]
